name: PHP coding standards

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    name: Lint PHP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Start the development environment
        run: npm run env start

      - name: Install Composer dependencies
        run: npm run test:php:install-deps

      - name: Lint PHPCS
        run: npm run lint:php:phpcs -- --report-full

      - name: Run PHPStan
        run: npm run lint:php:phpstan

