name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    name: Lint PHP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4' # Sync with required PHP version for the plugin.
          tools: composer

      - name: Install Composer dependencies
        run: composer install

      - name: Lint PHPCS
        run: composer lint:phpcs

      - name: Run PHPStan
        run: composer lint:phpstan
