name: Run PHPUnit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name for pull requests
  # or the commit hash for any other events.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  generate-matrix:
    name: Generate PHP and WP version testing matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate.outputs.matrix }}
    steps:
      - uses: actions/checkout@v6
      - name: Generate PHP and WP testing matrix
        id: generate
        run: echo "matrix=$(node ./bin/github-actions-matrix.js)" >> "$GITHUB_OUTPUT"

  phpunit:
    name: Run tests (WP ${{ matrix.wp-version }}, PHP ${{ matrix.php-version }})
    runs-on: ubuntu-latest
    needs: generate-matrix
    env:
      WP_ENV_PHP_VERSION: ${{ matrix.php-version }}
      WP_ENV_CORE: ${{ matrix.wp-version == 'trunk' && 'WordPress/WordPress' || format( 'https://wordpress.org/wordpress-{0}.zip', matrix.wp-version ) }}
    strategy:
      matrix: ${{ fromJSON( needs.generate-matrix.outputs.matrix ) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Setup cache
        uses: actions/cache@v5
        with:
          key: ${{ runner.os }}-${{ hashFiles('composer.json') }} # Note that lock file will change between runs.
          path: |
            .cache
            tests/phpunit/cache

      - name: Skip development plugins
        run: echo '{"plugins":[]}' > .wp-env.override.json

      - name: Start the development environment
        run: npm run env start

      - name: Report Versions
        run: |
          npm run env run cli -- php -v
          npm run env run cli -- wp core version

      - name: Install fresh dependencies for PHP ${{ matrix.php-version }}
        run: rm composer.lock

      - name: Install dependencies
        run: npm run cli -- composer require --dev phpunit/phpunit:^${{ matrix.wp-version < '5.1' && '6' || ( matrix.wp-version < '5.9' || matrix.php-version < '8.0' ) && '7' || '9' }}

      - name: Run PHPUnit tests (single site)
        run: npm run test:php

      - name: Run PHPUnit tests (multisite)
        run: npm run test:php:multisite

  phpunit-coverage:
    name: PHPUnit Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup cache
        uses: actions/cache@v5
        with:
          key: ${{ runner.os }}-${{ hashFiles('composer.json') }} # Note that lock file will change between runs.
          path: |
            .cache
            tests/phpunit/cache

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Start the development environment
        run: npm run env -- start --xdebug=coverage

      - name: Report Versions
        run: |
          npm run env run cli -- php -v
          npm run env run cli -- php -i | grep xdebug
          npm run env run cli -- wp core version

      - name: Install Composer dependencies
        run: npm run test:php:install-deps

      - name: Generate coverage report
        run: npm run coverage:php:full
